stages:
  - build
  - package

image: rustlang/rust:nightly

bin_build:
  stage: build
  artifacts:
    untracked: true
  script:
    - echo ${PUBLIC_KEY} > gateway/src/public_key.pem
    - echo ${CONFIG_FILE} > gateway/src/config.rs
    - cargo build --release

docker_build:
  image: docker:latest
  stage: package
  dependencies: 
    - bin_build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" --build-arg BRANCH=${CI_COMMIT_BRANCH} .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
