stages:
  - lints
  - test
  - build_base
  - build

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
cache:
  key:
    files:
      - Cargo.lock
  paths:
    # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
    - .cargo/bin
    - .cargo/registry/index
    - .cargo/registry/cache
    - .cargo/git/db

format:
  image: rust
  stage: lints
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

clippy:
  image: rust
  stage: lints
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --all -- -D warnings

test:
  image: rust
  stage: test
  script:
    - cargo test

docker_build_base:
  image: docker:latest
  stage: build_base
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from "$CI_REGISTRY_IMAGE:base_$CI_COMMIT_REF_SLUG" -t "$CI_REGISTRY_IMAGE:base_$CI_COMMIT_REF_SLUG" -f Dockerfile_base .
    - docker push "$CI_REGISTRY_IMAGE:base_$CI_COMMIT_REF_SLUG"

docker_build:
  image: docker:latest
  stage: build
  needs: ["docker_build_base"]
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" --build-arg BRANCH=${CI_COMMIT_BRANCH} .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
