- app_name: "/chartis"
  host: "127.0.0.1:8000"
  forward_path: "/chartis"
  mode:
    kind: "forward_strict"
    endpoints:
      - path: "/layer/{layerSlug}/mvt/{geoType}/"
        method: "GET"
- app_name: "/portal"
  host: "portal-configured-master-portal-configured:80"
  forward_path: ""
  mode:
    kind: "forward_all"
    endpoints:
