apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apidefinitions.gateway.bfor.fr
spec:
  group: gateway.bfor.fr
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                app_name:
                  type: string
                host:
                  type: string
                mode:
                  type: object
                  properties:
                    kind:
                      type: string
                      enum:
                        - forward_strict
                        - forward_all
                    endpoints:
                      type: array
                      items:
                        type: object
                        properties:
                          method:
                            type: string
                            enum:
                              - GET
                              - HEAD
                              - POST
                              - PUT
                              - DELETE
                              - CONNECT
                              - TRACE
                              - PATCH
                          path:
                            type: string
                forward_path:
                  type: string
  scope: Namespaced
  names:
    plural: apidefinitions
    singular: apidefinition
    kind: ApiDefinition
